module.exports = [
  {
    id: "2922c286-16cd-4d43-ab98-c79f698aeab0",
    user_id: "9b4f79ea-0e6c-4e59-8e05-afd933d0b3d3",
    address: "503 Broadway",
    city: "New York",
    state: "NY",
    country: "USA",
    area: "500sq ft",
    price: "5000",
    fees: "",
    availability: "",
    bedrooms: "1",
    bathrooms: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    features: "",
    amenities: "",
    pictures: "",
  },
  {
    id: "5bf7bd6c-2b16-4129-bddc-9d37ff8539e9",
    user_id: "83433026-ca32-4c6d-bd86-a39ee8b7303e",
    address: "33 Pearl Street SW",
    city: "Washington",
    state: "DC",
    country: "USA",
    area: "500sq ft",
    price: "5000",
    fees: "",
    availability: "",
    bedrooms: "1",
    bathrooms: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    features: "",
    amenities: "",
    pictures: "",
  },
  {
    id: "90ac3319-70d1-4a51-b91d-ba6c2464408c",
    user_id: "a193a6a7-42ab-4182-97dc-555ee85e7486",
    address: "300 Main Street",
    city: "New Jersey",
    state: "NJ",
    country: "USA",
    area: "500sq ft",
    price: "5000",
    fees: "",
    availability: "",
    bedrooms: "1",
    bathrooms: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    features: "",
    amenities: "",
    pictures: "",
  },
  {
    id: "bfc9bea7-66f1-44e9-879b-4d363a888eb5",
    user_id: "8f16bd30-bab5-40af-aca2-b63d5fdd1acc",
    address: "890 Brannnan Street",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    area: "500sq ft",
    price: "5000",
    fees: "",
    availability: "",
    bedrooms: "1",
    bathrooms: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    features: "",
    amenities: "",
    pictures: "",
  },
  {
    id: "bfc9bea7-66f1-44e9-879b-4d363a888eb4",
    user_id: "bdc6bb69-e09c-498d-8abd-be2792504d00",
    address: "890 Brannnan Street",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    area: "500sq ft",
    price: "5000",
    fees: "",
    availability: "",
    bedrooms: "1",
    bathrooms: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    features: "",
    amenities: "",
    pictures: "",
  },
  {
    id: "89898957-04ba-4bd0-9f5c-a7aea7447963",
    user_id: "3ce124a4-78b0-4d80-91b9-11f9ced631a7",
    address: "520 Broadway",
    city: "Santa Monica",
    state: "CA",
    country: "USA",
    area: "500sq ft",
    price: "5000",
    fees: "",
    availability: "",
    bedrooms: "1",
    bathrooms: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    features: "",
    amenities: "",
    pictures: "",
  },
  {
    id: "ade0a47b-cee6-4693-b4cd-a7e6cb25f4b7",
    user_id: "4dd464d6-90b8-4330-91e0-bd1217811bd9",
    address: "1201 Third Avenue",
    city: "Seattle",
    state: "WA",
    country: "USA",
    area: "500sq ft",
    price: "5000",
    fees: "",
    availability: "",
    bedrooms: "1",
    bathrooms: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    features: "",
    amenities: "",
    pictures: "",
  },
  {
    id: "bb1491eb-30e6-4728-a5fa-72f89feaf622",
    user_id: "c0ba64a8-0ecb-4a7d-ab7f-2dbbd1d437b1",
    address: "2650 NW 5th Avenue",
    city: "Miami",
    state: "FL",
    country: "USA",
    area: "500sq ft",
    price: "5000",
    fees: "",
    availability: "",
    bedrooms: "1",
    bathrooms: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    features: "",
    amenities: "",
    pictures: "",
  },
  {
    id: "150a36cf-f38e-4f59-8e31-39974207372d",
    user_id: "d9ef9352-2367-4272-8884-70cf80cb7a38",
    address: "215 Essex Street",
    city: "Boston",
    state: "MA",
    country: "USA",
    area: "500sq ft",
    price: "5000",
    fees: "",
    availability: "",
    bedrooms: "1",
    bathrooms: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    features: "",
    amenities: "",
    pictures: "",
  },
];
