module.exports = [
  {
    id: "150a36cf-f38e-4f59-8e31-39974207372d",
    user_id: "d9ef9352-2367-4272-8884-70cf80cb7a38",
    address: "123 Main St",
    city: "Anytown",
    state: "NY",
    country: "USA",
    area: "1000 sqft",
    price: "$1500/month",
    fees: "$100/month",
    availability: "Available now",
    bedrooms: "2",
    bathrooms: "1",
    description: "Cozy apartment in a quiet neighborhood",
    features: "Hardwood floors, balcony, fireplace",
    amenities: "Pool, gym, parking",
    type: "apartment",
    pets: true,
    pictures:
      "https://example.com/picture1.jpg,https:/example.com/picture2.jpg,https://example.com/picture3.jpg",
    lat: 40.730395,
    lng: -73.997963,
  },
  {
    id: "bb1491eb-30e6-4728-a5fa-72f89feaf622",
    user_id: "c0ba64a8-0ecb-4a7d-ab7f-2dbbd1d437b1",
    address: "456 Elm St",
    city: "Othertown",
    state: "NY",
    country: "USA",
    area: "1200 sqft",
    price: "$1800/month",
    fees: "$150/month",
    availability: "Available in 2 weeks",
    bedrooms: "3",
    bathrooms: "2",
    description: "Spacious apartment with great views",
    features: "Large windows, stainless steel appliances",
    amenities: "Gym, parking",
    type: "apartment",
    pets: false,
    pictures:
      "https://example.com/picture4.jpg,https://example.com/picture5.jpg,https://example.com/picture6.jpg",
    lat: 42.453416,
    lng: -76.473598,
  },
  {
    id: "ade0a47b-cee6-4693-b4cd-a7e6cb25f4b7",
    user_id: "4dd464d6-90b8-4330-91e0-bd1217811bd9",
    address: "789 Oak St",
    city: "Anothercity",
    state: "FL",
    country: "USA",
    area: "1500 sqft",
    price: "$2500/month",
    fees: "$200/month",
    availability: "Available next month",
    bedrooms: "4",
    bathrooms: "3",
    description: "Beautiful house with a backyard",
    features: "Hardwood floors, fireplace, backyard",
    amenities: "Pool, gym, parking",
    type: "house",
    pets: true,
    pictures:
      "https://example.com/picture7.jpg,https://example.com/picture8.jpg,https://example.com/picture9.jpg",
    lat: 40.724888,
    lng: -73.996311,
  },
  {
    id: "89898957-04ba-4bd0-9f5c-a7aea7447963",
    user_id: "3ce124a4-78b0-4d80-91b9-11f9ced631a7",
    address: "321 Pine St",
    city: "Sometown",
    state: "TX",
    country: "USA",
    area: "900 sqft",
    price: "$1200/month",
    fees: "$75/month",
    availability: "Available now",
    bedrooms: "1",
    bathrooms: "1",
    description: "Cozy studio apartment in downtown",
    features: "Hardwood floors, high ceilings",
    amenities: "Laundry, parking",
    type: "apartment",
    pets: true,
    pictures:
      "https://example.com/picture10.jpg,https://example.com/picture11.jpg,https://example.com/picture12.jpg",
    lat: 40.689247,
    lng: -74.044502,
  },
  {
    id: "bfc9bea7-66f1-44e9-879b-4d363a888eb4",
    user_id: "bdc6bb69-e09c-498d-8abd-be2792504d00",
    address: "654 Maple Ave",
    city: "Anycity",
    state: "IL",
    country: "USA",
    area: "1100 sqft",
    price: "$1700/month",
    fees: "$120/month",
    availability: "Available in 1 week",
    bedrooms: "2",
    bathrooms: "2",
    description: "Modern apartment with great views",
    features: "Large windows, balcony, hardwood floors",
    amenities: "Gym, pool, parking",
    type: "apartment",
    pets: false,
    pictures:
      "https://example.com/picture13.jpg,https://example.com/picture14.jpg,https://example.com/picture15.jpg",
    lat: 40.748817,
    lng: -73.985428,
  },
  {
    id: "bfc9bea7-66f1-44e9-879b-4d363a888eb5",
    user_id: "8f16bd30-bab5-40af-aca2-b63d5fdd1acc",
    address: "987 Cherry St",
    city: "Somewhere",
    state: "WA",
    country: "USA",
    area: "1800 sqft",
    price: "$2800/month",
    fees: "$250/month",
    availability: "Available next month",
    bedrooms: "3",
    bathrooms: "2",
    description: "Spacious house with backyard and pool",
    features: "Hardwood floors, fireplace, backyard, pool",
    amenities: "Gym, parking",
    type: "house",
    pets: true,
    pictures:
      "https://example.com/picture16.jpg,https://example.com/picture17.jpg,https://example.com/picture18.jpg",
    lat: 40.758896,
    lng: -73.98513,
  },
  {
    id: "7",
    user_id: "8f16bd30-bab5-40af-aca2-b63d5fdd1acc",
    address: "567 Oak St",
    city: "Everytown",
    state: "FL",
    country: "USA",
    area: "1500 sqft",
    price: "$2000/month",
    fees: "$150/month",
    availability: "Available now",
    bedrooms: "2",
    bathrooms: "2",
    description: "Luxury apartment in a high-rise building",
    features: "Balcony, stainless steel appliances",
    amenities: "Pool, gym, parking",
    type: "apartment",
    pets: false,
    pictures:
      "https://example.com/picture19.jpg,https://example.com/picture20.jp,https://example.com/picture21.jpg",
    lat: 40.782864,
    lng: -73.965355,
  },
  {
    id: "9",
    user_id: "a193a6a7-42ab-4182-97dc-555ee85e7486",
    address: "123 Main St",
    city: "Anytown",
    state: "NY",
    country: "USA",
    area: "800 sqft",
    price: "$1100/month",
    fees: "$100/month",
    availability: "Available now",
    bedrooms: "1",
    bathrooms: "1",
    description: "Cozy apartment in a quiet neighborhood",
    features: "Wooden floors, spacious kitchen",
    amenities: "Laundry, parking",
    type: "apartment",
    pets: true,
    pictures:
      "https://example.com/picture22.jpg,https://example.com/picture23.jpg,https://example.com/picture24.jpg",
    lat: 40.712732,
    lng: -74.013332,
  },
  {
    id: "5bf7bd6c-2b16-4129-bddc-9d37ff8539e9",
    user_id: "83433026-ca32-4c6d-bd86-a39ee8b7303e",
    address: "789 Elm St",
    city: "Nowhere",
    state: "CA",
    country: "USA",
    area: "2000 sqft",
    price: "$3500/month",
    fees: "$300/month",
    availability: "Available in 2 weeks",
    bedrooms: "3",
    bathrooms: "3",
    description: "Stunning house with ocean view",
    features: "Hardwood floors, fireplace, balcony, ocean view",
    amenities: "Pool, gym, parking",
    type: "house",
    pets: true,
    pictures:
      "https://example.com/picture25.jpg,https://example.com/picture26.jpg,https://example.com/picture27.jpg",
    lat: 40.706086,
    lng: -73.996864,
  },
  {
    id: "2922c286-16cd-4d43-ab98-c79f698aeab0",
    user_id: "9b4f79ea-0e6c-4e59-8e05-afd933d0b3d3",
    address: "111 Beach Blvd",
    city: "Beachtown",
    state: "FL",
    country: "USA",
    area: "1200 sqft",
    price: "$2200/month",
    fees: "$200/month",
    availability: "Available in 1 month",
    bedrooms: "2",
    bathrooms: "2",
    description: "Beachfront apartment with private access",
    features: "Balcony, ocean view, private beach access",
    amenities: "Pool, gym, parking",
    type: "apartment",
    pets: false,
    pictures:
      "https://example.com/picture28.jpg,https://example.com/picture29.jpg,https://example.com/picture30.jpg",
    lat: 40.779436,
    lng: -73.963244,
  },
  {
    id: "90ac3319-70d1-4a51-b91d-ba6c2464408c",
    user_id: "a193a6a7-42ab-4182-97dc-555ee85e7486",
    address: "999 Sunset Blvd",
    city: "Sunsetville",
    state: "CA",
    country: "USA",
    area: "1500 sqft",
    price: "$2500/month",
    fees: "$200/month",
    availability: "Available now",
    bedrooms: "2",
    bathrooms: "2",
    description: "Luxury apartment in a new building",
    features: "Balcony, stainless steel appliances, smart home technology",
    amenities: "Pool, gym, parking",
    type: "apartment",
    pets: true,
    pictures:
      "https://example.com/picture31.jpg,https://example.com/picture32.jpg,https://example.com/picture33.jpg",
    lat: 40.752726,
    lng: -73.977229,
  },
  {
    id: "13",
    user_id: "8f16bd30-bab5-40af-aca2-b63d5fdd1acc",
    address: "456 Oak St",
    city: "Greenville",
    state: "SC",
    country: "USA",
    area: "1000 sqft",
    price: "$1500/month",
    fees: "$150/month",
    availability: "Available in 3 weeks",
    bedrooms: "2",
    bathrooms: "1",
    description: "Recently renovated apartment with modern finishes",
    features: "New appliances, granite countertops",
    amenities: "Laundry, parking",
    type: "apartment",
    pets: true,
    pictures:
      "https://example.com/picture34.jpg,https://example.com/picture35.jpg,https://example.com/picture36.jpg",
    lat: 40.747992,
    lng: -74.004764,
  },
  {
    id: "14",
    user_id: "8f16bd30-bab5-40af-aca2-b63d5fdd1acc",
    address: "321 Pine St",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    area: "1800 sqft",
    price: "$2500/month",
    fees: "$200/month",
    availability: "Available now",
    bedrooms: "3",
    bathrooms: "2",
    description: "Spacious house in a great location",
    features: "Hardwood floors, fireplace",
    amenities: "Parking",
    type: "house",
    pets: true,
    pictures:
      "https://example.com/picture37.jpg,https://example.com/picture38.jpg,https://example.com/picture39.jpg",
    lat: 40.75874,
    lng: -73.978674,
  },
  {
    id: "15",
    user_id: "9b4f79ea-0e6c-4e59-8e05-afd933d0b3d3",
    address: "7777 Broadway",
    city: "New York",
    state: "NY",
    country: "USA",
    area: "1500 sqft",
    price: "$4000/month",
    fees: "$400/month",
    availability: "Available in 1 month",
    bedrooms: "2",
    bathrooms: "2",
    description: "Luxury apartment with stunning views of the city",
    features: "Floor-to-ceiling windows, high-end finishes",
    amenities: "Pool, gym, parking",
    type: "apartment",
    pets: false,
    pictures:
      "https://example.com/picture40.jpg,https://example.com/picture41.jpg,https://example.com/picture42.jpg",
    lat: 40.85062,
    lng: -73.878387,
  },
  {
    id: "16",
    user_id: "a193a6a7-42ab-4182-97dc-555ee85e7486",
    address: "555 Main St",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    area: "2000 sqft",
    price: "$5000/month",
    fees: "$500/month",
    availability: "Available now",
    bedrooms: "3",
    bathrooms: "3",
    description: "Luxurious penthouse with panoramic views of the city",
    features: "Private elevator, outdoor space",
    amenities: "Pool, gym, parking",
    type: "apartment",
    pets: true,
    pictures:
      "https://example.com/picture43.jpg,https://example.com/picture44.jpg,https://example.com/picture45.jpg",
    lat: 40.765151,
    lng: -73.979838,
  },
];
